sudo: required
dist: trusty
language: java
cache:
  directories:
  - "~/.m2"
jdk:
- oraclejdk8
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
install:
- 
after_success:
- bash <(curl -s https://codecov.io/bash)
- mvn com.gavinmogan:codacy-maven-plugin:coverage -DcoverageReportFile=target/site/jacoco/jacoco.xml -DprojectToken=$CODACY_PROJECT_TOKEN -DapiToken=$CODACY_PROJECT_TOKEN -DcodacyApiBaseUrl=https://api.codacy.com/
notifications:
  email:
    recipients:
      - almaslvl@gmail.com
    on_success: change
    on_failure: always
    on_start: never
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/afbf0239aac6566f24d4
    on_success: change
    on_failure: always
    on_start: never
env:
  matrix:
    secure: fRP4CU2qkv47HOd1PBrkGgwsP6To81AYuzi342fxnNTBv313c5fU+HCLYrYI5xNTYfE2b+Iax+A0ypbBbZ2XU+NtbI4OiAYCcBSiFOxFU/gty5neWvyRKG32qtUSNqdEPmx6EzdAjpFss3fyu6AB+g93SLC6S9IBiOxnS3av7cQ=
