os:
  - linux

# Ubuntu 16.04
dist: xenial
language: java
cache:
  directories:
  - "~/.m2"
services:
  - xvfb
jdk:
- openjdk11
- openjdk15
- openjdk-ea

before_install:
- echo "before_install NOOP"

install:
- echo "install NOOP"

script:
- mvn test -B -Dmaven.javadoc.skip=true -Djacoco.skip=true

deploy:
    # release dev build of FXGL to Sonatype
  - provider: script
    script: bash .github/.ci/deploy-sonatype.sh
    skip_cleanup: true
    # only notify when on "dev", not PR and JDK11 build succeeds
    on:
      branch: dev
      condition: $TRAVIS_PULL_REQUEST = false && $TRAVIS_JDK_VERSION = openjdk11
      
    # release dev build of FXGL dialogue editor
  - provider: script
    script: bash .github/.ci/notify-fxgl-dialogue-editor-builder.sh
    skip_cleanup: true
    # only notify when on "dev", not PR and JDK11 build succeeds
    on:
      branch: dev
      condition: $TRAVIS_PULL_REQUEST = false && $TRAVIS_JDK_VERSION = openjdk11
      
    # release dev build of FXGL
  - provider: script
    script: bash .github/.ci/notify-fxgl-builder.sh
    skip_cleanup: true
    # only notify when on "dev", not PR and JDK11 build succeeds
    on:
      branch: dev
      condition: $TRAVIS_PULL_REQUEST = false && $TRAVIS_JDK_VERSION = openjdk11

notifications:
  email:
    recipients:
    - almaslvl@gmail.com
    on_success: change
    on_failure: always
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/afbf0239aac6566f24d4
    on_success: change
    on_failure: always

env:
  global:
  - secure: fRP4CU2qkv47HOd1PBrkGgwsP6To81AYuzi342fxnNTBv313c5fU+HCLYrYI5xNTYfE2b+Iax+A0ypbBbZ2XU+NtbI4OiAYCcBSiFOxFU/gty5neWvyRKG32qtUSNqdEPmx6EzdAjpFss3fyu6AB+g93SLC6S9IBiOxnS3av7cQ=
  - secure: KU3KflYaq/91XNw9b5NB/7UskbVKhu6Ik5BTBoalTEqs2Jxw7kQns3jhRBCTrFgbik3B68UG4P+tHtLbz2z/MOnV7btHEm9b+hTi8jsU3BnaXI+V43vP04I6hO2fMAUilymw3lY8kzdmqX8imI6apvHuqVF/IYRS2ln5XGlMo10=
  - secure: aZQmJuxsNOdAB1G6CqVFIz0xQA8t4lKgT/Q3qvrUlikDhBHj+C6CkGd53VzqaHMwyKgknsHgXd7LKuCSdT4qR0oQbLx7PFJbvFbFiTVS8mLlLTPSVAkSfm9ObJydTEJSPYmENY93PN4QPw13gXHY2rhyE2cJ4O4GGR7pFSFQ5vo=
  - secure: B+A8Cj6g3VEDXRa1DiKLWNxS4SF+5PnKIdElzqGPQ6Nx9tCr0wkQfM/DoXvUHj87YSSlTsIughSGQ/kdYH59g9ZvvaBAvNBldMQSYPnRasYWE8J25ktcwb4Acm0RXKU8jqDHdFkPOzKBxyyeKsIndclPR0gIZZbOGXoPu+hlmB8=
  - secure: iLIk/h78/PMfPtEdcWcidRsBRDs1NdyAzHkPU+riNTvSAYcHhYKKpAck+Gub8LCQevlMVm6g4i1uT8ux7XJrE5rM90mpUP5V5510/4bW4oz+OmFDQLrXGFqh9glL5GxuVrFuDORsuIEPFRlyJ9yo8PLkk0DofCozy4awxv7QDgo=
  - secure: D+l91agoVIm73W9rPnJAR18BqIgxNvGxpCb2SBSzoZGHGBXTFrkffFBqYRJNeFe618h6YrRFYB1LvxFYfj5nKshKeHBjBA5kd29RA7fgcUNZYNJgqswOzpzwJNe9/Itq4Mda5u+m2aw1thYQ3D7GWRQ1Diu1JSRtM2N/3ts4cVA=
  - secure: Qm+NVyIxVTLbQmx9wD/JNdMyXHrdMmMqpGeIre8vq7PvA6F6NjVrzUbIYVIdspcxUtP8zrpLlhRQK62Ut6a5+CItNzj0hwf7lyHfErwePa+XmV7e/xrI0S6uD8dz/OKg4w2tIcwYvkHmCF/bAEV4IOXbFQRDaijNsOdS4z3azl8=
  - secure: OgSQVEHW9uu0A+qmRcJjrhfRRV1Ui8VQUPqYL37W0zqzxXFnLjEqGEGZjzCbc7IQSsiOmp//5xt729izSSBZamsQOAIgns8LR9CxM+tvRIQXxZNKLmRzD2aPKAkvmTPKarRYV8AC3y/aVOV6UIBT5DBr24uZGopRXU9NUeca1vQ=
