sudo: required

# Ubuntu 16.04
dist: xenial
language: java
cache:
  directories:
  - "~/.m2"
services:
  - xvfb
jdk:
- openjdk11
- openjdk12

install:
- 
after_success:
- bash <(curl -s https://codecov.io/bash)
- mvn com.gavinmogan:codacy-maven-plugin:coverage -DcoverageReportFile=fxgl/target/site/jacoco/jacoco.xml
  -DprojectToken=$CODACY_PROJECT_TOKEN -DapiToken=$CODACY_PROJECT_TOKEN -DcodacyApiBaseUrl=https://api.codacy.com/
- if [ "$TRAVIS_BRANCH" != "master" ]; then openssl aes-256-cbc -pass pass:$ENC_PASSWORD
  -in .travis/sign.asc.enc -out .travis/sign.asc -d; gpg -q --fast-import .travis/sign.asc;
  mvn deploy --settings .travis.settings.xml -DskipTests=true; chmod +x .travis/upload-build.sh; .travis/upload-build.sh; fi
notifications:
  email:
    recipients:
    - almaslvl@gmail.com
    on_success: change
    on_failure: always
    on_start: never
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/afbf0239aac6566f24d4
    on_success: change
    on_failure: always
    on_start: never
env:
  global:
  - secure: fRP4CU2qkv47HOd1PBrkGgwsP6To81AYuzi342fxnNTBv313c5fU+HCLYrYI5xNTYfE2b+Iax+A0ypbBbZ2XU+NtbI4OiAYCcBSiFOxFU/gty5neWvyRKG32qtUSNqdEPmx6EzdAjpFss3fyu6AB+g93SLC6S9IBiOxnS3av7cQ=
  - secure: KU3KflYaq/91XNw9b5NB/7UskbVKhu6Ik5BTBoalTEqs2Jxw7kQns3jhRBCTrFgbik3B68UG4P+tHtLbz2z/MOnV7btHEm9b+hTi8jsU3BnaXI+V43vP04I6hO2fMAUilymw3lY8kzdmqX8imI6apvHuqVF/IYRS2ln5XGlMo10=
  - secure: aZQmJuxsNOdAB1G6CqVFIz0xQA8t4lKgT/Q3qvrUlikDhBHj+C6CkGd53VzqaHMwyKgknsHgXd7LKuCSdT4qR0oQbLx7PFJbvFbFiTVS8mLlLTPSVAkSfm9ObJydTEJSPYmENY93PN4QPw13gXHY2rhyE2cJ4O4GGR7pFSFQ5vo=
  - secure: B+A8Cj6g3VEDXRa1DiKLWNxS4SF+5PnKIdElzqGPQ6Nx9tCr0wkQfM/DoXvUHj87YSSlTsIughSGQ/kdYH59g9ZvvaBAvNBldMQSYPnRasYWE8J25ktcwb4Acm0RXKU8jqDHdFkPOzKBxyyeKsIndclPR0gIZZbOGXoPu+hlmB8=
  - secure: iLIk/h78/PMfPtEdcWcidRsBRDs1NdyAzHkPU+riNTvSAYcHhYKKpAck+Gub8LCQevlMVm6g4i1uT8ux7XJrE5rM90mpUP5V5510/4bW4oz+OmFDQLrXGFqh9glL5GxuVrFuDORsuIEPFRlyJ9yo8PLkk0DofCozy4awxv7QDgo=
  - secure: D+l91agoVIm73W9rPnJAR18BqIgxNvGxpCb2SBSzoZGHGBXTFrkffFBqYRJNeFe618h6YrRFYB1LvxFYfj5nKshKeHBjBA5kd29RA7fgcUNZYNJgqswOzpzwJNe9/Itq4Mda5u+m2aw1thYQ3D7GWRQ1Diu1JSRtM2N/3ts4cVA=
  - secure: Qm+NVyIxVTLbQmx9wD/JNdMyXHrdMmMqpGeIre8vq7PvA6F6NjVrzUbIYVIdspcxUtP8zrpLlhRQK62Ut6a5+CItNzj0hwf7lyHfErwePa+XmV7e/xrI0S6uD8dz/OKg4w2tIcwYvkHmCF/bAEV4IOXbFQRDaijNsOdS4z3azl8=
  - secure: OgSQVEHW9uu0A+qmRcJjrhfRRV1Ui8VQUPqYL37W0zqzxXFnLjEqGEGZjzCbc7IQSsiOmp//5xt729izSSBZamsQOAIgns8LR9CxM+tvRIQXxZNKLmRzD2aPKAkvmTPKarRYV8AC3y/aVOV6UIBT5DBr24uZGopRXU9NUeca1vQ=
